from __future__ import annotations

from datetime import datetime
from pathlib import Path

from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    Image,
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

PAGE_WIDTH, PAGE_HEIGHT = A4
COLOR_HEADLINE = colors.HexColor("#1E1E1E")
COLOR_ACCENT = colors.HexColor("#00AFAF")
STATUS_COLORS = {
    "Stable": colors.HexColor("#388E3C"),
    "Watch": colors.HexColor("#F57C00"),
    "Critical": colors.HexColor("#D32F2F"),
}
TRANSLATIONS = {
    "de": {
        "title": "Sentra",
        "subtitle": "Frühwarnsystem für Shopify-Shops",
        "byline": "von Kevron Dynamics",
        "report_date": "Berichtsdatum",
        "status": "Status",
        "store": "Shop",
        "section_summary": "Kurzfazit",
        "section_metrics": "Kennzahlen",
        "section_chart": "Diagramm",
        "section_recommendations": "Interpretation & Empfehlungen",
        "section_kpi_explained": "KPIs erklärt",
        "section_next_checks": "Nächste Checks",
        "metric_last_7": "Umsatz (letzte 7 Tage)",
        "metric_previous_7": "Umsatz Vorperiode (7 Tage)",
        "metric_change": "Veränderung (%)",
        "metric_status": "Status",
        "chart_missing": "Diagramm nicht verfügbar.",
        "footer_generated": "Erstellt von Sentra",
        "footer_company": "Kevron Dynamics",
        "warnscore": "Warnscore",
        "kpi_last_7": "Umsatz letzte 7 Tage",
        "kpi_previous_7": "Umsatz vorherige 7 Tage",
        "kpi_change": "Veränderung in %",
        "kpi_status": "Statusbewertung",
        "next_checks": [
            "ROAS, Conversion-Rate und AOV in den letzten 7 Tagen prüfen.",
            "Traffic-Veränderungen nach Kanal und Kampagne vergleichen.",
            "Checkout-Abbrüche und Zahlungsfehler kurzfristig validieren.",
            "Top-Seller auf Verfügbarkeit, Preislogik und Rabattregeln prüfen.",
        ],
        "status_labels": {
            "Stable": "Stabil",
            "Watch": "Warnung",
            "Critical": "Kritisch",
        },
    },
    "en": {
        "title": "Sentra",
        "subtitle": "Early Warning for Shopify Stores",
        "byline": "by Kevron Dynamics",
        "report_date": "Report Date",
        "status": "Status",
        "store": "Store",
        "section_summary": "Executive Summary",
        "section_metrics": "Key Metrics",
        "section_chart": "Chart",
        "section_recommendations": "Interpretation & Recommendations",
        "section_kpi_explained": "KPI Explanation",
        "section_next_checks": "Next Checks",
        "metric_last_7": "Revenue (Last 7 Days)",
        "metric_previous_7": "Revenue (Previous 7 Days)",
        "metric_change": "Change (%)",
        "metric_status": "Status",
        "chart_missing": "Chart image not available.",
        "footer_generated": "Generated by Sentra",
        "footer_company": "Kevron Dynamics",
        "warnscore": "Warn score",
        "kpi_last_7": "Revenue last 7 days",
        "kpi_previous_7": "Revenue previous 7 days",
        "kpi_change": "Change in %",
        "kpi_status": "Status",
        "next_checks": [
            "Recheck ROAS, conversion rate and AOV for the last 7 days.",
            "Compare traffic shifts by channel and campaign.",
            "Validate checkout drop-offs and payment failures.",
            "Review top-seller stock, pricing and discount logic.",
        ],
        "status_labels": {
            "Stable": "Stable",
            "Watch": "Watch",
            "Critical": "Critical",
        },
    },
}
STATUS_ALIASES = {
    "stable": "Stable",
    "stabil": "Stable",
    "watch": "Watch",
    "warnung": "Watch",
    "critical": "Critical",
    "kritisch": "Critical",
}


def _resolve_language(language: str | None) -> str:
    raw = (language or "de").strip().lower()
    if raw.startswith("en"):
        return "en"
    return "de"


def _normalize_status(status_label: str) -> str:
    normalized = str(status_label or "").strip().lower()
    return STATUS_ALIASES.get(normalized, str(status_label))


def _status_color(status_label: str) -> colors.Color:
    return STATUS_COLORS.get(_normalize_status(status_label), COLOR_HEADLINE)


def _status_text(status_label: str, language: str) -> str:
    lang = _resolve_language(language)
    key = _normalize_status(status_label)
    return TRANSLATIONS[lang]["status_labels"].get(key, str(status_label))


def _register_sentra_fonts() -> tuple[str, str]:
    regular_name = "SentraSans"
    bold_name = "SentraSans-Bold"
    registered = set(pdfmetrics.getRegisteredFontNames())
    if regular_name in registered and bold_name in registered:
        return regular_name, bold_name

    font_candidates = [
        (Path("C:/Windows/Fonts/DejaVuSans.ttf"), Path("C:/Windows/Fonts/DejaVuSans-Bold.ttf")),
        (Path("C:/Windows/Fonts/arial.ttf"), Path("C:/Windows/Fonts/arialbd.ttf")),
    ]
    for regular_path, bold_path in font_candidates:
        if regular_path.exists() and bold_path.exists():
            pdfmetrics.registerFont(TTFont(regular_name, str(regular_path)))
            pdfmetrics.registerFont(TTFont(bold_name, str(bold_path)))
            return regular_name, bold_name

    return "Helvetica", "Helvetica-Bold"


def format_currency_eur(value: float) -> tuple[str, str]:
    formatted = f"{value:,.2f}"
    german = formatted.replace(",", "X").replace(".", ",").replace("X", ".")
    return german, "EUR"


def _currency(value: float) -> str:
    amount_str, currency = format_currency_eur(value)
    return f"{amount_str}\u00A0{currency}"


def _change(value: float) -> str:
    return f"{value:+.2f}".replace(".", ",") + "%"


def _build_status_badge(status_text: str, status_color: colors.Color, bold_font: str) -> Drawing:
    font_size = 9
    pad_x = 4.2 * mm
    text_width = pdfmetrics.stringWidth(status_text, bold_font, font_size)
    badge_width = max(30 * mm, text_width + (2 * pad_x))
    badge_height = 9 * mm

    badge = Drawing(badge_width, badge_height)
    badge.add(
        Rect(
            0,
            0,
            badge_width,
            badge_height,
            rx=2.5 * mm,
            ry=2.5 * mm,
            strokeColor=status_color,
            fillColor=status_color,
        )
    )
    badge.add(
        String(
            (badge_width - text_width) / 2,
            (badge_height - font_size) / 2 + (0.7 * mm),
            status_text,
            fontName=bold_font,
            fontSize=font_size,
            fillColor=colors.white,
        )
    )
    return badge


def _build_inline_badge(badge_text: str, badge_color: colors.Color, bold_font: str) -> Drawing:
    font_size = 8
    pad_x = 3.2 * mm
    text_width = pdfmetrics.stringWidth(badge_text, bold_font, font_size)
    badge_width = max(22 * mm, text_width + (2 * pad_x))
    badge_height = 7 * mm

    badge = Drawing(badge_width, badge_height)
    badge.add(
        Rect(
            0,
            0,
            badge_width,
            badge_height,
            rx=2.0 * mm,
            ry=2.0 * mm,
            strokeColor=badge_color,
            fillColor=badge_color,
        )
    )
    badge.add(
        String(
            (badge_width - text_width) / 2,
            (badge_height - font_size) / 2 + (0.5 * mm),
            badge_text,
            fontName=bold_font,
            fontSize=font_size,
            fillColor=colors.white,
        )
    )
    return badge


def _build_footer(language: str, regular_font: str):
    labels = TRANSLATIONS[_resolve_language(language)]

    def _draw_footer(canvas, doc) -> None:  # noqa: ANN001
        canvas.saveState()
        left = doc.leftMargin
        right = PAGE_WIDTH - doc.rightMargin
        y = 16 * mm

        canvas.setStrokeColor(COLOR_ACCENT)
        canvas.setLineWidth(0.8)
        canvas.line(left, y + 8 * mm, right, y + 8 * mm)

        canvas.setFillColor(COLOR_HEADLINE)
        canvas.setFont(regular_font, 9)
        canvas.drawString(left, y + 3.5 * mm, labels["footer_generated"])
        canvas.drawString(left, y, labels["footer_company"])
        canvas.restoreState()

    return _draw_footer


def generate_sentra_pdf(
    output_path: str,
    store_name: str,
    last_7_revenue: float,
    previous_7_revenue: float,
    change_percent: float,
    status_label: str,
    executive_summary: str,
    recommendations: list[str],
    chart_image_path: str,
    language: str = "de",
    warn_score: float | None = None,
) -> None:
    lang = _resolve_language(language)
    labels = TRANSLATIONS[lang]
    localized_status = _status_text(status_label, lang)
    regular_font, bold_font = _register_sentra_fonts()

    output = Path(output_path)
    if output.parent and str(output.parent) != ".":
        output.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=28 * mm,
        title=f"Sentra Bericht - {store_name}",
        pageCompression=0,
    )

    styles = getSampleStyleSheet()
    section_title = ParagraphStyle(
        "sentra-section-title",
        parent=styles["Heading3"],
        textColor=COLOR_HEADLINE,
        fontName=bold_font,
        fontSize=13,
        leading=16,
        spaceAfter=4,
    )
    body = ParagraphStyle(
        "sentra-body",
        parent=styles["BodyText"],
        fontName=regular_font,
        fontSize=10,
        leading=14,
        textColor=COLOR_HEADLINE,
    )
    muted = ParagraphStyle(
        "sentra-muted",
        parent=body,
        fontSize=9,
        textColor=colors.HexColor("#4E4E4E"),
    )
    kpi_value_style = ParagraphStyle(
        "kpi-value",
        parent=body,
        fontName=bold_font,
        fontSize=17,
        leading=19,
        alignment=1,
        splitLongWords=False,
        wordWrap="LTR",
    )
    kpi_label_style = ParagraphStyle(
        "kpi-label",
        parent=muted,
        fontName=regular_font,
        fontSize=7.8,
        leading=9.2,
        alignment=1,
    )

    story = []
    report_date = datetime.now().strftime("%d.%m.%Y")
    status_color = _status_color(status_label)
    status_badge = _build_status_badge(localized_status, status_color, bold_font)

    header_left = Paragraph(
        f"<font name='{bold_font}' size='28'>{labels['title']}</font><br/>"
        f"<font name='{regular_font}' size='10'>{labels['subtitle']}</font><br/>"
        f"<font name='{regular_font}' size='9'>{labels['byline']}</font>",
        body,
    )
    header_right = [
        Paragraph(f"<b>{labels['report_date']}:</b> {report_date}", muted),
        Spacer(1, 2 * mm),
        Paragraph(f"<b>{labels['status']}:</b>", muted),
        Spacer(1, 1.2 * mm),
        status_badge,
    ]
    header = Table([[header_left, header_right]], colWidths=[125 * mm, 43 * mm])
    header.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LINEBELOW", (0, 0), (-1, -1), 0.8, colors.HexColor("#DDEAF0")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(header)
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph(f"<b>{labels['store']}:</b> {store_name}", body))
    story.append(Spacer(1, 3 * mm))

    story.append(Paragraph(labels["section_summary"], section_title))
    summary_box = Table([[Paragraph(executive_summary, body)]], colWidths=[doc.width])
    summary_box.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EEF9F9")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#C9E6E6")),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(summary_box)
    story.append(Spacer(1, 5 * mm))

    story.append(Paragraph(labels["section_metrics"], section_title))

    card_width = doc.width / 4

    def _card(
        title: str,
        value: str,
        value_color: colors.Color = COLOR_HEADLINE,
        rich_value: bool = False,
    ) -> Table:
        value_font = bold_font
        card = Table(
            [
                [Paragraph(title, kpi_label_style)],
                [
                    Paragraph(
                        value,
                        ParagraphStyle(
                            "kpi-v",
                            parent=kpi_value_style,
                            fontName=value_font,
                            textColor=value_color,
                        ),
                    )
                ],
            ],
            colWidths=[card_width],
            rowHeights=[12 * mm, 15 * mm],
        )
        card.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                    ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E5E9EF")),
                    ("LINEBELOW", (0, 0), (-1, -1), 0.6, colors.HexColor("#EDF1F6")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        return card

    change_color = COLOR_HEADLINE
    if change_percent < 0:
        change_color = colors.HexColor("#D32F2F")
    elif change_percent > 0:
        change_color = colors.HexColor("#388E3C")

    last_7_amount, last_7_currency = format_currency_eur(last_7_revenue)
    prev_7_amount, prev_7_currency = format_currency_eur(previous_7_revenue)
    last_7_rich = (
        f"<nobr><font name='{bold_font}'>{last_7_amount}</font>"
        f"<font name='{regular_font}' size='11.3' color='#6B7280'>\u00A0{last_7_currency}</font></nobr>"
    )
    prev_7_rich = (
        f"<nobr><font name='{bold_font}'>{prev_7_amount}</font>"
        f"<font name='{regular_font}' size='11.3' color='#6B7280'>\u00A0{prev_7_currency}</font></nobr>"
    )

    metrics = Table(
        [
            [
                _card(labels["metric_last_7"], last_7_rich, rich_value=True),
                _card(labels["metric_previous_7"], prev_7_rich, rich_value=True),
                _card(labels["metric_change"], _change(change_percent), change_color),
                _card(labels["metric_status"], localized_status, status_color),
            ]
        ],
        colWidths=[card_width] * 4,
    )
    metrics.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    story.append(metrics)
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph(labels["section_chart"], section_title))
    chart_file = Path(chart_image_path)
    if chart_file.exists():
        chart = Image(str(chart_file))
        chart._restrictSize(doc.width - 2, 92 * mm)  # noqa: SLF001
        chart_wrap = Table([[chart]], colWidths=[doc.width])
        chart_wrap.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER")]))
        story.append(chart_wrap)
    else:
        story.append(Paragraph(labels["chart_missing"], muted))

    story.append(PageBreak())

    recommendation_items = [ListItem(Paragraph(str(text), body)) for text in recommendations]
    recommendation_list = ListFlowable(
        recommendation_items,
        bulletType="bullet",
        bulletFontName=regular_font,
        bulletFontSize=10,
        bulletColor=COLOR_ACCENT,
        leftPadding=3 * mm,
    )

    next_check_items = [ListItem(Paragraph(str(text), body)) for text in labels["next_checks"]]
    next_checks_list = ListFlowable(
        next_check_items,
        bulletType="bullet",
        bulletFontName=regular_font,
        bulletFontSize=10,
        bulletColor=COLOR_ACCENT,
        leftPadding=3 * mm,
    )

    section4_block = [
        Paragraph(labels["section_recommendations"], section_title),
        Spacer(1, 1.5 * mm),
        recommendation_list,
    ]
    section6_block = [
        Paragraph(labels["section_next_checks"], section_title),
        Spacer(1, 1.5 * mm),
        next_checks_list,
    ]
    two_col = Table([[section4_block, section6_block]], colWidths=[doc.width * 0.52, doc.width * 0.48])
    two_col.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (0, 0), 0),
                ("RIGHTPADDING", (0, 0), (0, 0), 5 * mm),
                ("LEFTPADDING", (1, 0), (1, 0), 5 * mm),
                ("RIGHTPADDING", (1, 0), (1, 0), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    story.append(two_col)
    story.append(Spacer(1, 3 * mm))

    divider = Table([[""]], colWidths=[doc.width])
    divider.setStyle(
        TableStyle(
            [
                ("LINEABOVE", (0, 0), (-1, -1), 0.8, colors.HexColor("#E4EAF0")),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    story.append(divider)
    story.append(Spacer(1, 3 * mm))

    story.append(Paragraph(labels["section_kpi_explained"], section_title))
    warnscore_line = "-" if warn_score is None else f"{warn_score:.1f}/100"
    warnscore_badge = _build_inline_badge(warnscore_line, status_color, bold_font)
    kpi_rows = [
        [labels["kpi_last_7"], _currency(last_7_revenue)],
        [labels["kpi_previous_7"], _currency(previous_7_revenue)],
        [labels["kpi_change"], _change(change_percent)],
        [labels["warnscore"], warnscore_badge],
        [labels["kpi_status"], localized_status],
    ]
    kpi_table = Table(kpi_rows, colWidths=[doc.width * 0.45, doc.width * 0.55])
    kpi_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), regular_font),
                ("FONTSIZE", (0, 0), (-1, -1), 9.6),
                ("TEXTCOLOR", (0, 0), (-1, -1), COLOR_HEADLINE),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#FAFCFD")]),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E5E9EF")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#EEF2F6")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    kpi_container = Table([[kpi_table]], colWidths=[doc.width])
    kpi_container.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F7FAFD")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#DCE6EF")),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(kpi_container)

    footer = _build_footer(lang, regular_font)
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
