from __future__ import annotations

from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    CondPageBreak,
    Image,
    KeepTogether,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

PAGE_WIDTH, PAGE_HEIGHT = A4
COLOR_HEADLINE = colors.HexColor("#1E1E1E")
COLOR_ACCENT = colors.HexColor("#00AFAF")
STATUS_COLORS = {
    "Stable": colors.HexColor("#2E7D32"),
    "Watch": colors.HexColor("#ED6C02"),
    "Critical": colors.HexColor("#C62828"),
}
TRANSLATIONS = {
    "de": {
        "title": "Sentra",
        "subtitle": "Fruehwarnsystem fuer Shopify-Shops",
        "byline": "von Kevron Dynamics",
        "report_date": "Berichtsdatum",
        "status": "Status",
        "store": "Shop",
        "section_summary": "Abschnitt 1 - Kurzfazit",
        "section_metrics": "Abschnitt 2 - Kennzahlen",
        "section_chart": "Abschnitt 3 - Diagramm",
        "section_recommendations": "Abschnitt 4 - Interpretation & Empfehlungen",
        "metric_last_7": "Umsatz (letzte 7 Tage)",
        "metric_previous_7": "Umsatz (vorherige 7 Tage)",
        "metric_change": "Veränderung (%)",
        "metric_status": "Status",
        "chart_missing": "Diagramm nicht verfuegbar.",
        "footer_generated": "Erstellt von Sentra",
        "footer_company": "Kevron Dynamics",
        "status_labels": {
            "Stable": "Stabil",
            "Watch": "Beobachten",
            "Critical": "Kritisch",
        },
    },
    "en": {
        "title": "Sentra",
        "subtitle": "Early Warning for Shopify Stores",
        "byline": "by Kevron Dynamics",
        "report_date": "Report Date",
        "status": "Status",
        "store": "Store",
        "section_summary": "SECTION 1 - Executive Summary",
        "section_metrics": "SECTION 2 - Key Metrics",
        "section_chart": "SECTION 3 - Chart",
        "section_recommendations": "SECTION 4 - Interpretation & Recommendations",
        "metric_last_7": "Revenue (Last 7 Days)",
        "metric_previous_7": "Revenue (Previous 7 Days)",
        "metric_change": "Change (%)",
        "metric_status": "Status",
        "chart_missing": "Chart image not available.",
        "footer_generated": "Generated by Sentra",
        "footer_company": "Kevron Dynamics",
        "status_labels": {
            "Stable": "Stable",
            "Watch": "Watch",
            "Critical": "Critical",
        },
    },
}
STATUS_ALIASES = {
    "stable": "Stable",
    "stabil": "Stable",
    "watch": "Watch",
    "beobachten": "Watch",
    "critical": "Critical",
    "kritisch": "Critical",
}


def _resolve_language(language: str | None) -> str:
    raw = (language or "de").strip().lower()
    if raw.startswith("en"):
        return "en"
    return "de"


def _normalize_status(status_label: str) -> str:
    normalized = str(status_label or "").strip().lower()
    return STATUS_ALIASES.get(normalized, str(status_label))


def _status_color(status_label: str) -> colors.Color:
    return STATUS_COLORS.get(_normalize_status(status_label), COLOR_HEADLINE)


def _status_text(status_label: str, language: str) -> str:
    lang = _resolve_language(language)
    key = _normalize_status(status_label)
    return TRANSLATIONS[lang]["status_labels"].get(key, str(status_label))


def _currency(value: float) -> str:
    return f"{value:,.2f} EUR"


def _change(value: float) -> str:
    return f"{value:+.2f}%"


def _build_footer(language: str):
    labels = TRANSLATIONS[_resolve_language(language)]

    def _draw_footer(canvas, doc) -> None:  # noqa: ANN001
        canvas.saveState()
        left = doc.leftMargin
        right = PAGE_WIDTH - doc.rightMargin
        y = 16 * mm

        canvas.setStrokeColor(COLOR_ACCENT)
        canvas.setLineWidth(0.8)
        canvas.line(left, y + 8 * mm, right, y + 8 * mm)

        canvas.setFillColor(COLOR_HEADLINE)
        canvas.setFont("Helvetica", 9)
        canvas.drawString(left, y + 3.5 * mm, labels["footer_generated"])
        canvas.drawString(left, y, labels["footer_company"])
        canvas.restoreState()

    return _draw_footer


def generate_sentra_pdf(
    output_path: str,
    store_name: str,
    last_7_revenue: float,
    previous_7_revenue: float,
    change_percent: float,
    status_label: str,
    executive_summary: str,
    recommendations: list[str],
    chart_image_path: str,
    language: str = "de",
) -> None:
    lang = _resolve_language(language)
    labels = TRANSLATIONS[lang]
    localized_status = _status_text(status_label, lang)

    output = Path(output_path)
    if output.parent and str(output.parent) != ".":
        output.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=28 * mm,
        title=f"Sentra Bericht - {store_name}",
        pageCompression=0,
    )

    styles = getSampleStyleSheet()
    section_title = ParagraphStyle(
        "sentra-section-title",
        parent=styles["Heading3"],
        textColor=COLOR_HEADLINE,
        fontName="Helvetica-Bold",
        fontSize=12,
        spaceAfter=5,
    )
    body = ParagraphStyle(
        "sentra-body",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=COLOR_HEADLINE,
    )
    muted = ParagraphStyle(
        "sentra-muted",
        parent=body,
        fontSize=9,
        textColor=colors.HexColor("#4E4E4E"),
    )
    section_title_keep = ParagraphStyle(
        "sentra-section-title-keep",
        parent=section_title,
        keepWithNext=True,
        spaceAfter=3,
    )

    story = []

    report_date = datetime.now().strftime("%d.%m.%Y")
    badge = Table([[localized_status]], colWidths=[32 * mm], rowHeights=[8 * mm])
    badge.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), _status_color(status_label)),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )

    header_left = Paragraph(
        f"<font size='19'><b>{labels['title']}</b></font><br/>"
        f"{labels['subtitle']}<br/>"
        f"{labels['byline']}",
        ParagraphStyle(
            "header-left",
            parent=body,
            textColor=COLOR_HEADLINE,
            leading=15,
        ),
    )
    header_right = [
        Paragraph(f"<b>{labels['report_date']}:</b> {report_date}", muted),
        Spacer(1, 2 * mm),
        Paragraph(f"<b>{labels['status']}:</b>", muted),
        Spacer(1, 1 * mm),
        badge,
    ]
    header = Table(
        [[header_left, header_right]],
        colWidths=[122 * mm, 46 * mm],
    )
    header.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LINEBELOW", (0, 0), (-1, -1), 1, COLOR_ACCENT),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(header)
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph(f"<b>{labels['store']}:</b> {store_name}", body))
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph(labels["section_summary"], section_title))
    summary_box = Table([[Paragraph(executive_summary, body)]], colWidths=[doc.width])
    summary_box.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EEF9F9")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#BFECEC")),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(summary_box)
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph(labels["section_metrics"], section_title))

    card_title_style = ParagraphStyle(
        "card-title",
        parent=muted,
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=colors.HexColor("#5A5A5A"),
        alignment=1,
    )
    card_value_style = ParagraphStyle(
        "card-value",
        parent=body,
        fontName="Helvetica-Bold",
        fontSize=11,
        alignment=1,
    )

    def _card(title: str, value: str, value_color: colors.Color = COLOR_HEADLINE) -> Table:
        value_style = ParagraphStyle(
            "card-value-dynamic",
            parent=card_value_style,
            textColor=value_color,
        )
        card = Table(
            [[Paragraph(title, card_title_style)], [Paragraph(value, value_style)]],
            colWidths=[doc.width / 4 - 4],
            rowHeights=[9 * mm, 11 * mm],
        )
        card.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFA")),
                    ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#DCEAEA")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]
            )
        )
        return card

    metrics = Table(
        [
            [
                _card(labels["metric_last_7"], _currency(last_7_revenue)),
                _card(labels["metric_previous_7"], _currency(previous_7_revenue)),
                _card(labels["metric_change"], _change(change_percent)),
                _card(labels["metric_status"], localized_status, _status_color(status_label)),
            ]
        ],
        colWidths=[doc.width / 4] * 4,
    )
    metrics.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    story.append(metrics)
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph(labels["section_chart"], section_title))
    chart_file = Path(chart_image_path)
    if chart_file.exists():
        chart = Image(str(chart_file))
        chart._restrictSize(doc.width - 8, 84 * mm)  # noqa: SLF001
        chart_wrap = Table([[chart]], colWidths=[doc.width])
        chart_wrap.setStyle(
            TableStyle(
                [
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        story.append(chart_wrap)
    else:
        story.append(Paragraph(labels["chart_missing"], muted))
    story.append(Spacer(1, 6 * mm))

    section4_header = Paragraph(labels["section_recommendations"], section_title_keep)
    recommendation_paragraphs = [Paragraph(str(text), body) for text in recommendations]
    recommendation_items = [ListItem(paragraph) for paragraph in recommendation_paragraphs]
    recommendation_list = ListFlowable(recommendation_items, bulletType="bullet")

    # ListFlowable.wrap needs a canvas; estimate required height from bullet paragraphs.
    estimated_list_height = 0.0
    if recommendation_paragraphs:
        for paragraph in recommendation_paragraphs:
            estimated_list_height += paragraph.wrap(doc.width - (10 * mm), doc.height)[1]
        estimated_list_height += max(0, len(recommendation_paragraphs) - 1) * (1.8 * mm)

    section4_height = (
        section4_header.wrap(doc.width, doc.height)[1]
        + (2 * mm)
        + estimated_list_height
    )
    story.append(CondPageBreak(section4_height + (2 * mm)))
    story.append(KeepTogether([section4_header, Spacer(1, 2 * mm), recommendation_list]))

    footer = _build_footer(lang)
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
